name: 'learn-github-actions'
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  check-bat-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Lint-Code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run test.py
        run: python test.py          
