name: 'learn-github-actions'
on: [push]
jobs:
  check-bat-version:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - run: npm install -g bats
      - run: bats -v
