name: 'learn-github-actions'
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  check-bat-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Lint Code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Setup Python
        uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9' 
      
      - name: Run Python
      - run: python test.py
